# Generated by Django 4.1.7 on 2023-05-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_rename_restaurant_name_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='ambiance_rating',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='overall_rating',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='review_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service_rating',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='taste_rating',
            field=models.FloatField(default=1, null=True),
        ),
    ]
