# Generated by Django 4.1.7 on 2023-05-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_ambiance_rating_restaurant_overall_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='model_id',
            field=models.IntegerField(default=1),
        ),
    ]
