def turkish_to_ascii(word):
    # Turkish characters and their ASCII equivalents
    chars = {'ı': 'i', 'İ': 'I', 'ş': 's', 'Ş': 'S', 'ğ': 'g', 'Ğ': 'G', 'ü': 'u', 'Ü': 'U', 'ö': 'o', 'Ö': 'O', 'ç': 'c', 'Ç': 'C'}
    
    # Replace each Turkish character in the word with its ASCII equivalent
    for turkish_char, ascii_char in chars.items():
        word = word.replace(turkish_char, ascii_char)
    
    return word

user_town = ""
def set_user_town(t):
  global user_town
  user_town = turkish_to_ascii(t)

def get_user_town():
  global user_town
  return user_town


rov = []
def set_rov(reason_list):
  global rov
  rov =[]
  rov.append(reason_list)
  rov = str(rov)
  

def get_rov():
  global rov
  return rov

user_id = 0
def set_user_id(n):
  global user_id
  user_id = n
  return user_id

def get_user_id():
  global user_id
  return user_id


import pandas as pd
restaurant_data = pd.DataFrame()
def initialize_restaurant_df():
  
  global restaurant_data
  restaurant_data = pd.read_csv("backend/Restaurant_OHE.csv")
  #print(restaurant_data.head())

def get_restaurant_df():
  global restaurant_data
  return restaurant_data

# Lists for Recommendation Model
features =  [
 'FastFood',
 'Coffee',
 'French',
 'Bakery',
 'Cafeteria',
 'Dutch',
 'Steaks',
 'Bar',
 'Sandwiches',
 'BarPubBrewery',
 'Burgers',
 'Seafood',
 'Asian',
 'LatinAmerican',
 'Juice',
 'Korean',
 'Greek',
 'Japanese',
 'Chinese',
 'Wine',
 'IceCream',
 'African',
 'American',
 'Vegetarian',
 'Contemporary',
 'Turkish',
 'Italian',
 'International',
 'Pizzeria',
 'Mexican',
 'wrap',
 'snacks',
 'boiled',
 'fresh',
 'sousage',
 'seafood',
 'risotto',
 'herbs',
 'mcncheese',
 'bread',
 'truffle',
 'salsa',
 'vegeterian',
 'fusion',
 'cake',
 'fish',
 'curry',
 'panini',
 'ramen',
 'tempura',
 'sandwich',
 'oil',
 'smoothie',
 'vegetable',
 'tapas',
 'cheese',
 'burger',
 'cocktail',
 'burrito',
 'chocolate',
 'stew',
 'doner',
 'bbq',
 'crab',
 'pizza',
 'wine',
 'meat',
 'noodle',
 'salty',
 'tea',
 'salad',
 'pubfood',
 'fermented',
 'pastry',
 'eclectic',
 'cofee',
 'fry',
 'fruit',
 'smoke',
 'sweet',
 'indigenous',
 'chicken',
 'snack',
 'spicy',
 'juice',
 'pasta',
 'aromatic',
 'global',
 'grill',
 'souce',
 'tex_mex',
 'taco',
 'waffle',
 'rice',
 'icecream',
 'beer',
 'tofu',
 'modern',
 'kimchi',
 'shrimp',
 'soup',
 'kebab',
 'patato',
 'sushi',
 'tomato',
 'charcuterie',
 'Guest',
 'Friend',
 'Work',
 'Date',
 'Family',
 'Family_profile',
 'Traveller',
 'Experiments',
 'Foodie',
 'Cinema',
 'Student',
 'SportsPerson',
 'StandUp',
 'Music',
 'Theatre',
 'Clasic',
 'Reading',
 'Businessman',
 'Hectic',
 'ESport',
 'Cozy',
 'Elegant',
 'CasualDining',
 'FineDining',
 'Ethnic',
 'Lively',
 'Sport',
 'FamilyFriendly',
 'Romantic']

context= ['Cozy_context',
 'Elegant_context',
 'CasualDining_context',
 'FineDining_context',
 'Ethnic_context',
 'Lively_context',
 'Sport_context',
 'FamilyFriendly_context',
 'Romantic_context',
 'Guest_context',
 'Friend_context',
 'Work_context',
 'Date_context',
 'Family_context',
 'Traveller_context',
 'Experiments_context',
 'Foodie_context',
 'Cinema_context',
 'Student_context',
 'SportsPerson_context',
 'StandUp_context',
 'Music_context',
 'Theatre_context',
 'Businessman_context',
 'Clasic_context',
 'Reading_context',
 'Family_profile_context',
 'Hectic_context',
 'ESport_context',
 'FastFood_context',
 'Coffee_context',
 'French_context',
 'Cafeteria_context',
 'Bakery_context',
 'Dutch_context',
 'Steaks_context',
 'Bar_context',
 'Sandwiches_context',
 'BarPubBrewery_context',
 'Burgers_context',
 'Seafood_context',
 'Asian_context',
 'LatinAmerican_context',
 'Juice_context',
 'Korean_context',
 'Greek_context',
 'Japanese_context',
 'Chinese_context',
 'Wine_context',
 'IceCream_context',
 'African_context',
 'American_context',
 'Vegetarian_context',
 'Contemporary_context',
 'Turkish_context',
 'Italian_context',
 'International_context',
 'Pizzeria_context',
 'Mexican_context',
 'boiled_context',
 'mcncheese_context',
 'risotto_context',
 'seafood_context',
 'bread_context',
 'salsa_context',
 'panini_context',
 'ramen_context',
 'sandwich_context',
 'tapas_context',
 'stew_context',
 'bbq_context',
 'meat_context',
 'salty_context',
 'cofee_context',
 'fruit_context',
 'diverse_context',
 'souvlaki_context',
 'juice_context',
 'grill_context',
 'rice_context',
 'taco_context',
 'icecream_context',
 'patato_context',
 'sushi_context',
 'tomato_context',
 'eclectic_context',
 'herbs_context',
 'sousage_context',
 'truffle_context',
 'vegeterian_context',
 'fusion_context',
 'cake_context',
 'curry_context',
 'smoothie_context',
 'crab_context',
 'pizza_context',
 'salad_context',
 'fry_context',
 'smoke_context',
 'waffle_context',
 'tofu_context',
 'mustard_context',
 'shrimp_context',
 'kebab_context',
 'wrap_context',
 'fresh_context',
 'baklava_context',
 'tempura_context',
 'world_context',
 'burrito_context',
 'chocolate_context',
 'cheese_context',
 'doner_context',
 'noodle_context',
 'tea_context',
 'fermented_context',
 'chicken_context',
 'snack_context',
 'spicy_context',
 'aromatic_context',
 'global_context',
 'souce_context',
 'beer_context',
 'modern_context',
 'soup_context',
 'tex_mex_context',
 'charcuterie_context',
 'feta_context',
 'snacks_context',
 'fish_context',
 'oil_context',
 'cocktail_context',
 'vegetable_context',
 'burger_context',
 'wine_context',
 'pubfood_context',
 'pastry_context',
 'umami_context',
 'sweet_context',
 'indigenous_context',
 'pasta_context',
 'kimchi_context']

features_ambiance = ['Work',
 'Date',
 'Guest',
 'Friend',
 'Family',
 'Reading',
 'ESport',
 'Student',
 'Music',
 'Experiments',
 'Theatre',
 'StandUp',
 'Businessman',
 'Clasic',
 'SportsPerson',
 'Cinema',
 'Foodie',
 'Traveller',
 'Hectic',
 'Family_profile',
 'CasualDining',
 'Ethnic',
 'FamilyFriendly',
 'Elegant',
 'Cozy',
 'FineDining',
 'Sport',
 'Romantic',
 'Lively']

context_ambiance =['CasualDining_context',
 'Ethnic_context',
 'FamilyFriendly_context',
 'Elegant_context',
 'Cozy_context',
 'FineDining_context',
 'Sport_context',
 'Romantic_context',
 'Lively_context',
 'Work_context',
 'Date_context',
 'Guest_context',
 'Friend_context',
 'Family_context',
 'ESport_context',
 'Reading_context',
 'Student_context',
 'Music_context',
 'Experiments_context',
 'StandUp_context',
 'Theatre_context',
 'Businessman_context',
 'SportsPerson_context',
 'Clasic_context',
 'Cinema_context',
 'Foodie_context',
 'Traveller_context',
 'Hectic_context',
 'Family_profile_context']

features_taste = ['salsa',
 'curry',
 'noodle',
 'soup',
 'herbs',
 'aromatic',
 'stew',
 'wrap',
 'tempura',
 'meat',
 'waffle',
 'fresh',
 'snacks',
 'tex_mex',
 'cheese',
 'vegeterian',
 'truffle',
 'bread',
 'risotto',
 'pasta',
 'sandwich',
 'tomato',
 'seafood',
 'doner',
 'burger',
 'juice',
 'beer',
 'charcuterie',
 'modern',
 'tofu',
 'patato',
 'fish',
 'sushi',
 'salad',
 'burrito',
 'pastry',
 'bbq',
 'fry',
 'chocolate',
 'taco',
 'tapas',
 'kebab',
 'smoke',
 'oil',
 'spicy',
 'grill',
 'cofee',
 'kimchi',
 'wine',
 'global',
 'snack',
 'tea',
 'shrimp',
 'fusion',
 'mcncheese',
 'sousage',
 'pizza',
 'fruit',
 'chicken',
 'smoothie',
 'souce',
 'fermented',
 'indigenous',
 'rice',
 'sweet',
 'panini',
 'boiled',
 'pubfood',
 'cocktail',
 'crab',
 'vegetable',
 'salty',
 'eclectic',
 'cake',
 'icecream',
 'ramen',
 'Asian',
 'Vegetarian',
 'Japanese',
 'Mexican',
 'Wine',
 'Greek',
 'Coffee',
 'Burgers',
 'Pizzeria',
 'Contemporary',
 'Bar',
 'LatinAmerican',
 'Chinese',
 'Seafood',
 'Italian',
 'Korean',
 'Cafeteria',
 'Juice',
 'Dutch',
 'FastFood',
 'Bakery',
 'American',
 'French',
 'Turkish',
 'African',
 'Sandwiches',
 'IceCream',
 'International',
 'BarPubBrewery',
 'Steaks']

context_taste = ['Asian_context',
 'Vegetarian_context',
 'Japanese_context',
 'Mexican_context',
 'Wine_context',
 'Greek_context',
 'Coffee_context',
 'Burgers_context',
 'Pizzeria_context',
 'Contemporary_context',
 'Bar_context',
 'LatinAmerican_context',
 'Chinese_context',
 'Korean_context',
 'Italian_context',
 'Seafood_context',
 'Cafeteria_context',
 'Juice_context',
 'Dutch_context',
 'FastFood_context',
 'Bakery_context',
 'American_context',
 'French_context',
 'Turkish_context',
 'African_context',
 'IceCream_context',
 'International_context',
 'BarPubBrewery_context',
 'Sandwiches_context',
 'Steaks_context',
 'noodle_context',
 'soup_context',
 'meat_context',
 'fresh_context',
 'snacks_context',
 'mustard_context',
 'seafood_context',
 'burger_context',
 'beer_context',
 'juice_context',
 'fish_context',
 'smoke_context',
 'mcncheese_context',
 'snack_context',
 'shrimp_context',
 'fruit_context',
 'pubfood_context',
 'cocktail_context',
 'indigenous_context',
 'diverse_context',
 'wrap_context',
 'cheese_context',
 'sushi_context',
 'salad_context',
 'burrito_context',
 'kebab_context',
 'souvlaki_context',
 'grill_context',
 'cofee_context',
 'kimchi_context',
 'fermented_context',
 'baklava_context',
 'cake_context',
 'ramen_context',
 'salsa_context',
 'aromatic_context',
 'stew_context',
 'tempura_context',
 'waffle_context',
 'tex_mex_context',
 'truffle_context',
 'bread_context',
 'pasta_context',
 'sandwich_context',
 'tomato_context',
 'umami_context',
 'world_context',
 'doner_context',
 'charcuterie_context',
 'modern_context',
 'tofu_context',
 'pastry_context',
 'chocolate_context',
 'oil_context',
 'tapas_context',
 'wine_context',
 'global_context',
 'fusion_context',
 'sousage_context',
 'chicken_context',
 'smoothie_context',
 'sweet_context',
 'panini_context',
 'boiled_context',
 'crab_context',
 'vegetable_context',
 'eclectic_context',
 'curry_context',
 'herbs_context',
 'vegeterian_context',
 'risotto_context',
 'patato_context',
 'bbq_context',
 'fry_context',
 'taco_context',
 'spicy_context',
 'tea_context',
 'pizza_context',
 'feta_context',
 'souce_context',
 'rice_context',
 'salty_context',
 'icecream_context']

all_cuisines =  [ 'FastFood',
 'Coffee',
 'French',
 'Bakery',
 'Cafeteria',
 'Dutch',
 'Steaks',
 'Bar',
 'Sandwiches',
 'BarPubBrewery',
 'Burgers',
 'Seafood',
 'Asian',
 'LatinAmerican',
 'Juice',
 'Korean',
 'Greek',
 'Japanese',
 'Chinese',
 'Wine',
 'IceCream',
 'African',
 'American',
 'Vegetarian',
 'Contemporary',
 'Turkish',
 'Italian',
 'International',
 'Pizzeria',
 'Mexican']

# getters
def get_features():
   global features
   return features

def get_context():
   global context
   return context

def get_features_ambiance():
   global features_ambiance
   return features_ambiance

def get_context_ambiance():
   global context_ambiance
   return context_ambiance

def get_features_taste():
   global features_taste
   return features_taste

def get_context_taste():
   global context_taste
   return context_taste

def get_all_cuisines():
   global all_cuisines
   return all_cuisines
