# Generated by Django 4.1.7 on 2023-04-20 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('restaurants', '0003_rename_restaurant_name_restaurant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiance_rating', models.IntegerField(default=1)),
                ('taste_rating', models.IntegerField(default=1)),
                ('service_rating', models.IntegerField(default=1)),
                ('customer_need_fast_slow', models.CharField(max_length=30)),
                ('reason_of_visit', models.CharField(max_length=50)),
                ('overall_rating', models.FloatField(default=1)),
                ('review_customer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('review_restaurant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
    ]
