# Generated by Django 4.1.7 on 2023-05-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resreview',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
